#spring.profiles.active=dev

logging:
  level:
    com:
      journal:
        journalApp: DEBUG

spring:


  application:
    name: journalApp
  data:
    redis:
      host: redis-10256.c305.ap-south-1-1.ec2.cloud.redislabs.com
      password: zvcSdU2ji7oncep5s6JswkP5H97Ykb1s
      port: 10256
    mongodb:
      uri: mongodb+srv://garvroc9_db_user:garvsharma@cluster0.xweqsf8.mongodb.net/?appName=Cluster0
      database: journaldb
      mongodb:
        auto-index-creation: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: garvroc9@gmail.com
    password: lhqp ryie pspx qmmh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
weather:
  api:
    key: 38d81855b0adadf230afa26b9f31aedb




